version: '3'

services:
  mysql:
    image: 'mysql:8.1'
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_DATABASE: 'ecommerce'
      MYSQL_USER: 'db_user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - 'mysql_data:/var/lib/mysql'

   

  django_demo:
    build:
      context: .
    container_name: django_demo
    ports:
      - "8000:8000"
    depends_on:
      - mysql

volumes:
  mysql_data:
    driver: local

